version:2.1
workflows:
   - name: test-deploy
     jobs:
       - test
jobs:
  test:
    docker: 
      - image: cimg/node:22.8.0
    steps:
      - checkout
      - run: node --version

      
      
