version:2.1

jobs:
  test:
    docker: 
      - image: centos:centos7
    steps:
      - checkout
      - run: 
          name: Run Tests
          command: npm --version
workflows:
  test-deploy
      jobs:
        - test
      
      
