version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2024.09
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: echo "sleeping for 30 sec"
      - run: sleep 30
  test:
    docker:
      - image: cimg/base:2024.09
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
