version:2.1

jobs:
  test:
    docker: 
      - image: cimg/node:22.8.0
    steps:
      - checkout
      - run: node --version
 workflows:
   test-deploy:
     jobs:
       - test
    

      
      
